theme = "mellow"

[editor]
mouse = false
cursorline = true
completion-timeout = 0
auto-info = false
indent-guides.render = true
indent-guides.skip-levels = 1
true-color = true

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer"]
