use-grammars = { only = [ "go", "typescript", "zig", "c", "html" ] }

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }
snippets-ls-ts = { command = "snippets-ls", args = ["-config", "C:\\_env\\snippets\\javascript\\typescript.json"] }
snippets-ls-go = { command = "snippets-ls", args = ["-config", "/root/.config/snippets/go.json"] }
snippets-ls-html = { command = "snippets-ls", args = ["-config", "C:\\_env\\snippets\\html.json"] }
gopls = { command = "gopls", config = { "gofumpt" = true, "local" = "goimports", "semanticTokens" = true, "staticcheck" = true, "verboseOutput" = true, "analyses" = { "fieldalignment" = true, "nilness" = true, unusedparams = true, unusedwrite = true, useany = true }, usePlaceholders = true, completeUnimported = true, hints = { "assignVariableType" = true, "compositeLiteralFields" = true, "compositeLiteralTypes" = true, "constantValues" = true, "functionTypeParameters" = true, "parameterNames" = true, "rangeVariableTypes" = true } } }

[[language]]
name = "go"
language-servers = ["gopls", "snippets-ls-go"]
auto-format = true

[[language]]
name = "zig"
auto-format = true

[[language]]
name = "html"
file-types = ["html", "htm", "zmpl"]
formatter = { command = "tidy", args = ["-ibq"]}
language-servers = [ "snippets-ls-html"]
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "biome" , args = ["format", "--stdin-file-path", "placeholder.ts"] }
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "snippets-ls-ts" ]
auto-format = true

[[language]]
name = "json"
formatter = { command = "biome" , args = ["format", "--stdin-file-path", "placeholder.json"] }
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true
